//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPorftolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int Id { get; set; }
        public string Descriptions { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Natioanly { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public string SpkenLang { get; set; }
        public string Image { get; set; }
    }
}
