//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPorftolioProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A4653D_panah01Entities : DbContext
    {
        public DB_A4653D_panah01Entities()
            : base("name=DB_A4653D_panah01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Backskil> Backskil { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Exprience> Exprience { get; set; }
        public virtual DbSet<Frontskil> Frontskil { get; set; }
        public virtual DbSet<Porftilio> Porftilio { get; set; }
        public virtual DbSet<UserComment> UserComment { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
    }
}
