//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPorftolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exprience
    {
        public int Id { get; set; }
        public string Companyname { get; set; }
        public string Companyspecial { get; set; }
        public string Minidesc { get; set; }
    }
}
