//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPorftolioProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Porftilio
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Client { get; set; }
        public string Duation { get; set; }
        public string UsedTech { get; set; }
        public string LinlUrl { get; set; }
    }
}
